import Head from 'next/head'
import Image from 'next/image'
// import Navbar from '../components/Navbar'

// API Key
// 9f562365939a4e94a85684951acd9b41

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navbar /> */}
      <div className="text flex flex-col justify-center items-center h-screen">
        <h1 className="text-3xl font-bold underline">
          Next js News App
        </h1>
        <p className='text-xl'>Your One Stop Shops For The Latest News & Articles.</p>
      </div>
    </div>
  )
}
